nama =input("Nama:")
nim  =input("Nim:")
kelas =input("Kelas Paralel:")
tetal =input("Tempat/Tanggal Lahir :")
alamat=input("Alamat           :")
hobby=input("Hobby            :")
nohp=input("No. HP          :")
print("Nama                 :",nama)
print("NIM                  :",nim)
print("Kelas Paralel        :",kelas)
print("Tempat/Tanggal Lahir :",tetal)
print("Alamat               :",alamat)
print("Hobby                :",hobby)
print("No. HP               :",nohp)
